<a href="https://colab.research.google.com/github/Anushka-Agrawal/ClassificatioN-Model/blob/master/Thoracic_Surgery_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest classification

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('ThoracicSurgery (classification data).csv')
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

## Encoding categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,4] = le.fit_transform(x[:,4])
x[:,5] = le.fit_transform(x[:,5])
x[:,6] = le.fit_transform(x[:,6])
x[:,7] = le.fit_transform(x[:,7])
x[:,8] = le.fit_transform(x[:,8])
x[:,11] = le.fit_transform(x[:,11])
x[:,10] = le.fit_transform(x[:,10])
x[:,12] = le.fit_transform(x[:,12])
x[:,13] = le.fit_transform(x[:,13])
x[:,3] = le.fit_transform(x[:,3])
x[:,9] = le.fit_transform(x[:,9])
print(x)

[['DGN2' 2.88 2.16 ... 0 1 60]
 ['DGN3' 3.4 1.88 ... 0 1 51]
 ['DGN3' 2.76 2.08 ... 0 1 59]
 ...
 ['DGN3' 3.04 2.08 ... 0 0 52]
 ['DGN3' 1.96 1.68 ... 0 1 79]
 ['DGN3' 4.72 3.56 ... 0 1 51]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
ct_2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 0.0 ... 0 1 60]
 [0.0 1.0 0.0 ... 0 1 51]
 [0.0 1.0 0.0 ... 0 1 59]
 ...
 [0.0 1.0 0.0 ... 0 0 52]
 [0.0 1.0 0.0 ... 0 1 79]
 [0.0 1.0 0.0 ... 0 1 51]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.55, random_state=0)

#feature scalling for Logistic regression classification

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy')
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(np.array(x_test))
print(np.concatenate((y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1))))

[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]


Checking the Model Performance


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[218   9]
 [ 28   4]]


0.8571428571428571